/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cic;

import java.util.*;
import java.io.*;
import javax.swing.*;

public class PowerNote extends javax.swing.JFrame {

    /**
     * Creates new form PowerNote
     */
    public PowerNote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pwer Note");

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("listo");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Desencriptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Encriptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.jLabel1.setText("abriendo...");
        
        this.jTextArea1.setText("");
        
        // 1. Crear un FileChooser
        JFileChooser fc = new JFileChooser();
        
        // 2. Mostrar la caja de diálogo
        int result = fc.showOpenDialog(this);
        
        // 3. Checar si se pulsó el botón abrir
        if (result == JFileChooser.APPROVE_OPTION) {
            // 4. Recuperar el archivo seleccionado
            File f = fc.getSelectedFile();
            
            try {
                // 5. Leer el archivo seleccionado
                FileReader fr = new FileReader(f);
                
                // 6. Scanear el archivo
                Scanner sc = new Scanner(fr);
                
                // 7. Linea por linea mientras tenga
                while (sc.hasNext()) {
                    String linea = sc.nextLine();
                    this.jTextArea1.append(linea + "\r\n");
                }
                
                fr.close();
                this.jLabel1.setText("listo");
            } catch(Exception e) {
                this.jLabel1.setText("error al abrir");
            }
        } else {
            this.jLabel1.setText("cancelado");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jLabel1.setText("guardando...");
        
        // 1. Crear un FileChooser
        JFileChooser fc = new JFileChooser();
        
        // 2. Abrir el FC en modo "guardar"
        int result = fc.showSaveDialog(this);
        
        // 3. Checar si ee pulsó el botón guardar
        if (result == JFileChooser.APPROVE_OPTION) {
            // 4. Rescuperar el archivo seleccionado
            File f = fc.getSelectedFile();
            
            // 5. Checar si el archivo existe
            if (f.exists()) {
                // 6. Mostrar un ConfirmDialog
                int result2 = JOptionPane.showConfirmDialog(
                    this,
                    "¿Desea reemplazar el archivo?",
                    "El archivo ya existe",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE
                );
                
                // 7. Checar si el usuario cancela
                if (result2 != JOptionPane.YES_OPTION) {
                    // No hay nada que hacer :(
                    return;
                }
                
                // Se va a reemplazar el archivo
                
                // 8. Guardar el archivo
                try {
                    FileWriter fw = new FileWriter(f);
                    
                    fw.write(this.jTextArea1.getText());
                    
                    fw.close();
                    
                    this.jLabel1.setText("listo");
                } catch(Exception e) {
                    this.jLabel1.setText("error al guardar");
                }
            }
        } else {
            this.jLabel1.setText("cancelado");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jLabel1.setText("encriptando...");
        
        // 1. Mostrar una caja de diálogo para pedir un número
        String result = JOptionPane.showInputDialog(this,
                "Ingresa la clave:", "0");
        
        // 2. Convertir el resultado en un entero k
        int k = 0;
        try {
         k = Integer.parseInt(result);
        } catch(Exception e) {
            this.jLabel1.setText("clave inválida");
            return; // No hay nada que hacer :(
        }
        
        // 3. Recuperar el contenido
        String text = this.jTextArea1.getText();
        
        // 4. Encriptar la cadena texto en la cadena text_enc
        String text_enc = "";
        
        // 5. Recorrer cada caracter de text
        for (char c : text.toCharArray()) {
            int cp = c + k;
            // Convetimos un entero en caracter
            text_enc += String.format("%c", cp);
        }
        
        // 6. Ponemos el resultado en el TextArea
        this.jTextArea1.setText(text_enc);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jLabel1.setText("encriptando...");
        
        // 1. Mostrar una caja de diálogo para pedir un número
        String result = JOptionPane.showInputDialog(this,
                "Ingresa la clave:", "0");
        
        // 2. Convertir el resultado en un entero k
        int k = 0;
        try {
         k = Integer.parseInt(result);
        } catch(Exception e) {
            this.jLabel1.setText("clave inválida");
            return; // No hay nada que hacer :(
        }
        
        // 3. Recuperar el contenido
        String text = this.jTextArea1.getText();
        
        // 4. Encriptar la cadena texto en la cadena text_enc
        String text_enc = "";
        
        // 5. Recorrer cada caracter de text
        for (char c : text.toCharArray()) {
            int cp = c - k;
            
            if (cp < 0) {
                cp += 256;
            }
            // Convetimos un entero en caracter
            text_enc += String.format("%c", cp);
        }
        
        // 6. Ponemos el resultado en el TextArea
        this.jTextArea1.setText(text_enc);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PowerNote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
